server:
 port: 8484

spring:
 autoconfigure:
  exclude:
   - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
 data:
  mongodb:
   uri: mongodb://localhost:27017/rhythm_db

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    songs: songs
    images: images
    covers: covers


