server:
  port: 8484
  servlet:
    context-path: /content

spring:
  application:
    name: content-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/rhythm_db
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    songs: songs
    images: images
    covers: covers

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

aes:
  secret-key: Unl0aE1vRnNPdUwxMkAqNw==

identity-service:
  base-url: http://localhost:8080/identity