server:
  port: 8888

app:
  api-prefix: /api/v1
  services:
    identity: http://localhost:8080
    content: http://localhost:8484
    notification: http://localhost:8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=2
      routes:
        - id: identity-service
          uri: ${app.services.identity}
          predicates:
            - Path=${app.api-prefix}/**
        - id: content-service
          uri: ${app.services.content}
          predicates:
            - Path=${app.api-prefix}/contents/**
        - id: notification-service
          uri: ${app.services.notification}
          predicates:
            - Path=${app.api-prefix}/notifications/**