server:
  port: 1122
  tomcat:
    threads:
      max: 200 #
      min-spare: 50
    #    max-connections: 8000
    accept-count: 20000

spring:
  application:
    name: rythm.com
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/music_social}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent-output: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5
      #          max-wait: -1ms
      connect-timeout: 30000

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /

  threads:
    virtual:
      enabled: true

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    songs: songs
    images: images
    covers: covers

jwt:
  signerKey: ""

aes:
  secret-key:

identity-service:
  base-url: http://localhost:8080/identity

resilience4j:
  circuitbreaker:
    instances:
      checkRandom:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        #        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      identity:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      notification:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
#    prometheus:
#      enabled: true